### ISSUE TITLE
Still Not Working?

### ISSUE THREAD

**Issue by oshipper** [bitpay/magento-plugin#100]
Is anyone actually using this on a live store? There are still ToDo's in the code and incomplete order status functionality.

I can find no examples of any live magento sites using or any developers who have (successfully) installed. Bitpay why do you let this languish for so long? This will be 2 holiday seasons in a row you missed.

**Comment by aleitner** [comment]
Last I checked the plugin release works without a problem with Magento 1.8, 1.8.1, and 1.9

See releases here:
https://github.com/bitpay/magento-plugin/releases/tag/v2.1.10
http://www.magentocommerce.com/magento-connect/bitpay-bitcoin-payment-method.html

**Comment by oshipper** [comment]
@aleitner So does that mean you have seen this actually working on a real store taking real order and updating order status in magento admin correctly when payments are completed?

 That has not been my experience the last 2 times I've checked the code; a year apart. Nothing in change logs indicates this was addressed since then as most commits are 2 years old.

 No budget left to check this another time as most clients went with Coinbase (and their working extension). 1 client still has bitpay but gave up on bitcoin in general when Bitpay failed to address anything for 2 holidays in a row.

Tell me it actually works in real life with a real merchant and real customers and I'll check it again

**Comment by kleetus** [comment]
Yes, this plugin works just fine and real customers use it. 

No, I am not going to provide a customer by name (this is not BitPay's policy). The best I can provide is public data that Magento Connect provides which you can view within your Magento Connect account.

**Comment by oshipper** [comment]
Not asking for an example. Just that you understand the issues in past with no mechanism for changing order status on payment (literally a To Do in the code) and that this has since been finished. You, @kleetus, can say without hesitation that professional merchants have been able to use it in a production environment without issue.

I can't charge to review/test this extension again so appreciate not wasting my time if this is not the case.
