### ISSUE TITLE
Use BitPay's new invoice

### ISSUE THREAD

**Issue by ajp8164** [bitpay/magento-plugin#110]

**Comment by HeliumRaccoon** [comment]
bitpay new invoice not created in live transaction on order submit button click

**Comment by pieterpoorthuis** [comment]
Helium,

What's your ecommerce website URL?
Also make sure that your live account is fully verified, and that the minimum order value is $1

**Comment by pieterpoorthuis** [comment]
BitPay's new invoice is now used by default

**Comment by HeliumRaccoon** [comment]
Can you upload demo video of bitpay working on magento
