### ISSUE TITLE
Min/max order settings are reported to not work correctly

### ISSUE THREAD

**Issue by ajp8164** [bitpay/magento-plugin#111]

**Comment by pieterpoorthuis** [comment]
Invoices on test have a $0.04 minimum. On production the minimum is currently $5. BitPay may change the minimum in the future, so we cannot hardcode the minimum in the plugin.

When BitPay returns an error during invoice creation, the plugin should display this error to the customer.
Example JSON error message that BitPay returns:
{ error: 'Invoice price must be at least $0.04 USD' }

Please use the value in the error message to display to the customer.

**Comment by pieterpoorthuis** [comment]
Fixed in release 2.1.18
