### ISSUE TITLE
Files Missing in 2.1.15 / Unable to Pair

### ISSUE THREAD

**Issue by zaximus84** [bitpay/magento-plugin#114]
After installing release 2.1.15 (master at this time), I was unable to pair. This error was present in the log:

In Bitpay_Core_Helper_Data::registerAutoloader(): autoloader file was not found or is not readable. Cannot continue!

Upon further investigation, I discovered that method attempts to find lib/Bitpay/Autoloader.php. That file is non-existent in 2.1.15. The only thing in lib/Bitpay is lib/Bitpay/Storage/MagentoStorage.php. I downloaded the version from Magento Connect (supposedly 2.1.14) and it has many files and directories in lib/Bitpay. When I install that version, I am able to pair.

**Comment by pieterpoorthuis** [comment]
If you install from the source, you need to run composer to pull in the libraries & autoloader.

The releases (zip/tgz) already contain the libraries & autoloader: https://github.com/bitpay/magento-plugin/releases, because
