### ISSUE TITLE
Expired Invoice - Wrong Redirect

### ISSUE THREAD

**Issue by HairLossTalk** [bitpay/magento-plugin#117]
1)	Allow an invoice to expire
2)	Displays “What happened?  Your invoice expired.  Invoices only last 15 minutes.  What can you do now?  You can return to Online Health Networks Inc, and try your purchase again…”
3)	Online Health Networks Inc links to my “redirect” URL:   /shop/checkout/onepage/success/
4)	It should not redirect to this page.  This page is for successful orders.  It should redirect to the cart page so they can try the payment again.

**Comment by pieterpoorthuis** [comment]
Fixed in release 2.1.18
