### ISSUE TITLE
After paying from any other bitcoin, invoice is not generating using IPN

### ISSUE THREAD

**Issue by HeliumRaccoon** [bitpay/magento-plugin#118]
Bitpay does not support any other bitcoin wallet user processing and it takes ages for any non bitpay wallet user to pay on bitpay payment method on Magento. 
It redirects to bitpay page with QR code and non bitpay wallet user scan QR code wait for next century to get bitcoin processed

**Comment by pieterpoorthuis** [comment]
BitPay supports all payment protocol compatible wallets.

For more information, see https://blog.bitpay.com/payment-protocol-results/
