### ISSUE TITLE
Unable to Pair Magento with BitPay

### ISSUE THREAD

**Issue by King-of-Vapes** [bitpay/magento-plugin#119]
Hello guys! We are having some frustrating issues with this module. First, the Ruby commands given on BitPay documentation had some spelling and capitalization issues that caused TWO WEEKS of errors and frustrations. After that was finally sorted out and the Merchant Facade was created, we tried pairing with Magento and have been unable to. Support from BitPay has been unresponsive for two weeks. Here's the error log report for the issue:

"2017-10-01T03:48:58+00:00 DEBUG (7): Array
(
    [0] => [ERROR] Exception thrown while calling the sendPairingRequest() function. The specific error message is: "In Bitpay_Core_Helper_Data::registerAutoloader(): autoloader file was not found or is not readable. Cannot continue!"
    [__pid] => 14286"

We would appreciate any help from the community regarding this issue. We have reinstalled the module in case the file was missing, no dice. We also tried creating a whole new pairing code, that didn't work either. Anyone faced this before? Thanks in advance.

UPDATE: The "autoloader.php" file was indeed missing from lib/BitPay. We added the file found here: https://github.com/bitpay/php-bitpay-client/blob/master/src/Bitpay/Autoloader.php, and same error is occuring.

**Comment by pieterpoorthuis** [comment]
The error your get indicates you downloaded the source from github, but you did not download the 3rd party libraries. Did you read the installation documentation: https://github.com/bitpay/magento-plugin/blob/master/GUIDE.md

Easiest is to install a prepackaged release from https://github.com/bitpay/magento-plugin/releases

If you install from source, you need to install 3rd party libraries (using composer) and package it up yourself.

**Comment by King-of-Vapes** [comment]
Hello Pieter. Thanks, we found that out the hard way. :). We were able to pair with a Point of Sale Facade. We created a Merchant Facade, but it refused to pair with the Merchant Facade. Any reason for that?


King of Vapes
Hector- Sales Dept.
: (844) 465-8273
: (201) 722-0840
: www.kingofvapes.guru

LET'S CONNECT!

**Comment by pieterpoorthuis** [comment]
The Magento module has created to work with the POS facade. Not for any other facade.

**Comment by technweb** [comment]
installed via modman same error, what are the 3rd party libraries are we missing? where can I find the list. Note: your module is no longer available since Magento Connect was sunset.

**Comment by pieterpoorthuis** [comment]
3rd parties libraries are listed in composer.json. The Bitpay_Core zip files in each release contain the libraries and the autolader. Latest release is https://github.com/bitpay/magento-plugin/releases/download/v2.1.15/Bitpay_Core-2.1.15.zip

Server requirements are described in GUIDE.md
