### ISSUE TITLE
After clicked place order button

### ISSUE THREAD

**Issue by comfo** [bitpay/magento-plugin#120]
Hello,
My problem is after clicked the place order button. When clicked it, it is redirect to bitpay payment page. but I see payment valided in magento. But I don't made any payment. Have you any idea ?

Screenshoot : https://image.noelshack.com/fichiers/2017/48/4/1512057966-problem.jpg

**Comment by comfo** [comment]
Hello Pieter,
Yes I am sure. I used 2.1.15. But problem continue...
What to do need ?

**Comment by pieterpoorthuis** [comment]
Please send an email to support@bitpay.com , including var/log/payment_bitpay.log

I'll pick it up from there

**Comment by comfo** [comment]
I sent you Mr. Pieter.

**Comment by pieterpoorthuis** [comment]
Magento 1.8.1.0 related.

**Comment by comfo** [comment]
Hello,
When you fix it ?
Regards

**Comment by HeliumRaccoon** [comment]
there is problem release zip file 2.1.15 release is actually has no change and module is not same version till 2.1.9, why there is shadow releases ? please release correct version

**Comment by HeliumRaccoon** [comment]
Only 1 change is detected <depends> <Mage_Payment/></depends>
![screen shot 2017-12-17 at 6 42 28 pm](https://user-images.githubusercontent.com/4976216/34080591-2ace774a-e35a-11e7-82b8-2380dbd31805.png)
difference b/w 2.1.9 and 2.1.15 in screen shot

**Comment by pieterpoorthuis** [comment]
Helium,

There have been 28 commits since release 2.1.9, see https://github.com/bitpay/magento-plugin/compare/v2.1.9...master

Which files are you using for your comparison?

**Comment by comfo** [comment]
hello, did you fixed my problem ?

**Comment by pieterpoorthuis** [comment]
Fixed in release 2.1.18
