### ISSUE TITLE
IPN creates after payment a second invoice in database instead of update invoice

### ISSUE THREAD

**Issue by MacProFreak** [bitpay/magento-plugin#121]
Hi,
I'm using magento ce 1.9.3.7 and implemented latest magento-plugin 2.1.15.
When a customer paid his order with the bitpay module then a second entry in sales_flat_order_payment is created instead of update the invoice entry in the table.
This second payment entry in sales_flat_order_payment creates a failure in the order overview in magento backend. (Item (Mage_Sales_Model_Order) with the same id "6021" already exist)

My research find in the IpnController.php the problem in line 115 (Comment // Update the order to notifiy that it has been paid). In this if condition on $order->addPayment($payment); should have been make an update payment and not a new payment. Or?

Could you help to fix the problem?

Best regards,
Erich

**Comment by HeliumRaccoon** [comment]
which version do you have that create an invoice on submit order button on magento checkout page

**Comment by HeliumRaccoon** [comment]
there are two kind of invoices in Bitpay module, first invoices are stored for bitpay invoice table for bitpay_invoices and bitpay_ipn table, 2nd magento order invoice .
in Magento admin order view there is no invoice generating that is real issue

**Comment by MacProFreak** [comment]
Hi,
sorry for my late answer but I'm on holiday and have no access to the code. But I donwloaded the latest code version from this repo. 
Could you find a solution for missing invoice creation in magento?
We changed the method addPayment to updatePayment to avoid to create a second invoice in magento table. This is our temporarily solution but we would prefer a fix from your side.

Best regards,
Erich

**Comment by HeliumRaccoon** [comment]
As soon I will test new fix on my system and if it will work fine, I would love to commit on this repo, But untill then I am only writing real test case scenarios for magento bitpay

**Comment by pieterpoorthuis** [comment]
Fixed in release 2.1.18
