### ISSUE TITLE
There is no apikeys configuration on system.xml based on observer code

### ISSUE THREAD

**Issue by HeliumRaccoon** [bitpay/magento-plugin#122]
[Observer](url) |: app/code/community/Bitpay/Core/Model/Observer.php 
line 25 function checkForRequest code missing  
line 33: apikey configuration doesnot exist in system.xml in following file
app/code/community/Bitpay/Core/etc/system.xml
also in Model classes, there are missing codes
So end result there is huge missing code and that's why it is not working

**Comment by pieterpoorthuis** [comment]
Fixed in release 2.1.18
