### ISSUE TITLE
Magento marketplace compatibility

### ISSUE THREAD

**Issue by pieterpoorthuis** [bitpay/magento-plugin#126]
This plugin needs to be compatible with Magento marketplace, so we can host it there.

**Comment by HeliumRaccoon** [comment]
your extension is not published by magento marketplace because it's buggy

**Comment by pieterpoorthuis** [comment]
BitPay's plugin is now available on the Magento Marketplace: https://marketplace.magento.com/bitpay-bitpay-core.html
