### ISSUE TITLE
Having stable dependencies in composer.json

### ISSUE THREAD

**Issue by nicolas-ifg** [bitpay/magento-plugin#127]
dependency to `php-client` is pointing a dev branch commit which makes me doing dirty thing to get the last versions (> 2.1.5) installed.
https://github.com/bitpay/magento-plugin/blob/master/composer.json#L16

Do you plan to get that fixed ?

**Comment by pieterpoorthuis** [comment]
yes. We are working on a big update, including pointing composer.json to BitPay's stable PHP library

**Comment by HeliumRaccoon** [comment]
Any deadline for new version ?

**Comment by pieterpoorthuis** [comment]
Fixed in release 2.1.18
