### ISSUE TITLE
Hardcode transactionSpeed to medium

### ISSUE THREAD

**Issue by pieterpoorthuis** [bitpay/magento-plugin#144]
To simplify the Magento BitPay configuration, the 'transactionSpeed' selection has been removed.
The plugin however still fetches the transactionSpeed from the database.

Three things need to be done:
1) The plugin should set transactionSpeed=medium everywhere (IpnController.php, invoice.php, etc).
2) The IpnController business logic can then be simplified, as there is only 1 transactionSpeed
3) The IpnController now sometimes doesn't create a Magento invoice when the Paid IPN is received. It would be better if the IpnController always checks if an invoice exists if a valid IPN comes in (status paid, confirmed or complete). If there is no Magento invoice, the IpnController should create one. The reason is that even with medium speed the 'paid' IPN is mostly sent, but not always.

**Comment by nicolas-ifg** [comment]
Does it mean that we can not set the transaction speed to low anymore ? Or the IPN is sent according to the parameter in the Bitpay account ?

**Comment by pieterpoorthuis** [comment]
It means the BitPay invoice will be set to 'medium' speed, overriding the BitPay account setting.

When a BitPay invoice is paid, BitPay will send 'paid' -> 'confirmed' -> 'complete'. You can map these values to your liking to a Magento order status.

**Comment by pieterpoorthuis** [comment]
Yes. That's the advantage of medium speed: BitPay sends 'paid', followed by 'confirmed', followed by 'complete'.

**Comment by pieterpoorthuis** [comment]
Fixed in PR #147
