### ISSUE TITLE
Expired invoices not being cancelled?

### ISSUE THREAD

**Issue by JonLaliberte** [bitpay/magento-plugin#148]
For some time I've had a problem that I thought would be addressed by the module - invoices that are not paid are not automatically cancelled after the invoice has expired.

I was surprised to find that back in 2014 there was a pull request that was merged to add this feature: https://github.com/bitpay/magento-plugin/pull/68

It looks like this was removed [here](https://github.com/bitpay/magento-plugin/commit/8371f891258e96b3d89c36882088e5cad8223d0f#diff-8a22c5e5ea59b63ecbac94f7c226dcee), but never re-added.

The remnants of it are still in the code, but the `cleanExpired` function doesn't seem to be defined anywhere.

https://github.com/bitpay/magento-plugin/blob/6f8a6b647bebd1e08ce5c0d8401b9ce25637fd62/app/code/community/Bitpay/Core/Model/Observer.php#L73-L76

If I'm wrong, and this function is still being performed somewhere - it doesn't seem to be working for me, any idea what I should be checking for?

**Comment by JonLaliberte** [comment]
> Check question: what happens if a customer checks out, creates a BitPay invoice, hits 'back' in his browser and creates another BitPay invoice? Would the first BitPay invoice cancel the full order?

I don't think that would cause any problems. As-is I believe that each BitPay invoice created is a 1 to 1 mapping with a Magento order (correct me if I'm wrong on this). So the first invoice expiring should then just cancel the first order, the second order and invoice wouldn't affect the first order. Although it would be useful if there were a way to know that that second invoice cancels the original, the expiration via IPN would be a sufficient solution.

This is a bit beyond my knowledge of the module code right now to get it in place correctly/quickly (and unfortunately a lack of time). Currently this causes some mild to medium sized headaches as those non-cancelled orders cause inventory values to be incorrect (this isn't a problem most of the time, but becomes one when I forget to clear these invoices out manually).

**Comment by pieterpoorthuis** [comment]
Fixed in PR #152
